---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - warden.scality.com
  resources:
  - noderemediationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - warden.scality.com
  resources:
  - noderemediationpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - warden.scality.com
  resources:
  - noderemediationpolicies/status
  verbs:
  - get
  - patch
  - update
