//go:build !ignore_autogenerated

/*
Copyright 2026 Scality.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionMatch) DeepCopyInto(out *ConditionMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionMatch.
func (in *ConditionMatch) DeepCopy() *ConditionMatch {
	if in == nil {
		return nil
	}
	out := new(ConditionMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Debounce) DeepCopyInto(out *Debounce) {
	*out = *in
	if in.Enter != nil {
		in, out := &in.Enter, &out.Enter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Exit != nil {
		in, out := &in.Exit, &out.Exit
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Debounce.
func (in *Debounce) DeepCopy() *Debounce {
	if in == nil {
		return nil
	}
	out := new(Debounce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Guard) DeepCopyInto(out *Guard) {
	*out = *in
	if in.MaxAffectedPercent != nil {
		in, out := &in.MaxAffectedPercent, &out.MaxAffectedPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Guard.
func (in *Guard) DeepCopy() *Guard {
	if in == nil {
		return nil
	}
	out := new(Guard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRemediationPolicy) DeepCopyInto(out *NodeRemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRemediationPolicy.
func (in *NodeRemediationPolicy) DeepCopy() *NodeRemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(NodeRemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeRemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRemediationPolicyList) DeepCopyInto(out *NodeRemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeRemediationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRemediationPolicyList.
func (in *NodeRemediationPolicyList) DeepCopy() *NodeRemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(NodeRemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeRemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRemediationPolicySpec) DeepCopyInto(out *NodeRemediationPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Condition = in.Condition
	in.Remediations.DeepCopyInto(&out.Remediations)
	in.Debounce.DeepCopyInto(&out.Debounce)
	in.Guard.DeepCopyInto(&out.Guard)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRemediationPolicySpec.
func (in *NodeRemediationPolicySpec) DeepCopy() *NodeRemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NodeRemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRemediationPolicyStatus) DeepCopyInto(out *NodeRemediationPolicyStatus) {
	*out = *in
	if in.SelectedNodes != nil {
		in, out := &in.SelectedNodes, &out.SelectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchedNodes != nil {
		in, out := &in.MatchedNodes, &out.MatchedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PendingNodes != nil {
		in, out := &in.PendingNodes, &out.PendingNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnknownNodes != nil {
		in, out := &in.UnknownNodes, &out.UnknownNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HeldNodes != nil {
		in, out := &in.HeldNodes, &out.HeldNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemediatedNodes != nil {
		in, out := &in.RemediatedNodes, &out.RemediatedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRemediationPolicyStatus.
func (in *NodeRemediationPolicyStatus) DeepCopy() *NodeRemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NodeRemediationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Remediations) DeepCopyInto(out *Remediations) {
	*out = *in
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = new(corev1.Taint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Remediations.
func (in *Remediations) DeepCopy() *Remediations {
	if in == nil {
		return nil
	}
	out := new(Remediations)
	in.DeepCopyInto(out)
	return out
}
